import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import MainNavigation from '@/components/main-navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <MainNavigation />
                <main className={`min-w-full min-h-page flex bg-[#19191900]`}>
                    {children}
                </main>
            </body>
        </html>
    )
}
